version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/mobtimer?schema=public
    ports:
      - 3001:3001
    depends_on:
      - postgres
    links:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
      POSTGRES_DB: mob-timer
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: