-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "breakcount" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "breaktime" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "maintimer" TIMESTAMP(3),
ADD COLUMN     "members" TEXT[],
ADD COLUMN     "topic" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "worktime" INTEGER NOT NULL DEFAULT 15;
